version: "3.3"

services:
  image:
    image: ${TARGET_IMAGE_NAME}:${BASE_IMAGE_VERSION}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE_NAME}:${BASE_IMAGE_VERSION}
